<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.0" />
	  <PackageReference Include="YamlDotNet" Version="16.3.0" />
	  <PackageReference Include="Common.Logging" Version="3.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JackSharp\JackSharp.csproj" />
  </ItemGroup></Project>
